In [41]:
import cvxpy as cp
import numpy as np

def optimize_weights_for_forecast_steps(returns_matrix, cov_matrices, max_variance):
    num_steps, num_stocks = returns_matrix.shape
    optimal_weights_matrix = np.zeros((num_steps, num_stocks))

    for step in range(num_steps):
        returns = returns_matrix[step, :]
        cov_matrix = cov_matrices[step, :, :]

        # Define the variables
        weights = cp.Variable(num_stocks)

        # Define the objective function (negative because cvxpy minimizes)
        objective = cp.Maximize(-cp.sum(cp.multiply(returns, weights)))

        # Define the constraints
        constraints = [
            cp.sum(weights) == 1,
            weights >= 0,
            cp.quad_form(weights, cov_matrix) <= max_variance  # You can replace max_variance with your specific constraint
        ]

        # Formulate the problem
        problem = cp.Problem(objective, constraints)

        # Solve the problem with error handling
        try:
            problem.solve()
            optimal_weights_matrix[step, :] = weights.value
        except cp.error.SolverError:
            print(f"Optimization failed for step {step}. Check data or adjust constraints.")
            optimal_weights_matrix[step, :] = np.nan

    return optimal_weights_matrix

# Example usage
num_steps = 5  # Number of forecast steps
num_stocks = 3  # Number of stocks
returns_matrix = np.random.rand(num_steps, num_stocks)  # Replace with your mean forecast matrix
variances_matrix = np.random.rand(num_steps, num_stocks)  # Replace with your variance forecast matrix
cov_matrices = np.array([np.diag(variances) for variances in variances_matrix])  # Assuming independent stocks for simplicity
max_variance = 0.2  # Replace with your specific constraint on variance

optimal_weights_matrix = optimize_weights_for_forecast_steps(returns_matrix, cov_matrices, max_variance)

print("Optimal Weights Matrix:")
print(optimal_weights_matrix)


Optimal Weights Matrix:
[[4.14462272e-01 5.85537727e-01 1.82335965e-10]
 [2.35261693e-01 3.76897934e-01 3.87840373e-01]
 [1.55864682e-01 5.51219934e-09 8.44135312e-01]
 [1.54523750e-01 5.11083215e-01 3.34393036e-01]
 [3.94476913e-02 4.56842637e-01 5.03709672e-01]]


In [43]:
optimal_weights_matrix.sum(axis=1)

array([1., 1., 1., 1., 1.])

In [46]:
import numpy as np
from scipy.optimize import minimize

def objective(weights, returns, cov_matrix):
    portfolio_return = np.dot(returns, weights)
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = -portfolio_return / portfolio_volatility  # Minimize the negative Sharpe ratio
    return sharpe_ratio

def optimize_portfolio(returns, cov_matrix, max_variance):
    num_stocks = len(returns)

    # Constraint: weights sum to 1
    constraints = ({'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1},
                   {'type': 'ineq', 'fun': lambda weights: max_variance - np.dot(weights.T, np.dot(cov_matrix, weights))})

    # Initial guess: Equal weights
    initial_weights = np.ones(num_stocks) / num_stocks

    # Minimize the negative Sharpe ratio
    result = minimize(objective, initial_weights, args=(returns, cov_matrix), method='SLSQP', constraints=constraints)

    optimal_weights = result.x

    return optimal_weights

# Example usage
num_stocks = 3
returns = np.array([0.5, 0.8, 0.12])  # Replace with your mean forecast for each stock
variances = np.array([0.02, 0.03, 0.05])  # Replace with your variance forecast for each stock
cov_matrix = np.diag(variances)  # Assuming independent stocks for simplicity
max_variance = 0.1  # Replace with your specific constraint on variance

optimal_weights = optimize_portfolio(returns, cov_matrix, max_variance)

print("Optimal Weights:", optimal_weights)


Optimal Weights: [0.46239913 0.49318054 0.04442033]


In [47]:
optimal_weights.sum()

1.0

In [ ]:
import cvxpy as cp
import numpy as np

def optimize_weights_for_forecast_steps(returns_matrix, cov_matrices, max_variance):
    num_steps, num_stocks = returns_matrix.shape
    optimal_weights_matrix = np.zeros((num_steps, num_stocks))

    for step in range(num_steps):
        returns = returns_matrix[step, :]
        cov_matrix = cov_matrices[step, :, :]

        # Define the variables
        weights = cp.Variable(num_stocks)

        # Define the objective function (negative because cvxpy minimizes)
        objective = cp.Maximize(-cp.sum(cp.multiply(returns, weights)))

        # Define the constraints
        constraints = [
            cp.sum(weights) == 1,
            weights >= 0,
            cp.quad_form(weights, cov_matrix) <= max_variance  # You can replace max_variance with your specific constraint
        ]

        # Formulate the problem
        problem = cp.Problem(objective, constraints)

        # Solve the problem with error handling
        try:
            problem.solve()
            optimal_weights_matrix[step, :] = weights.value
        except cp.error.SolverError:
            print(f"Optimization failed for step {step}. Check data or adjust constraints.")
            optimal_weights_matrix[step, :] = np.nan

    return optimal_weights_matrix

# Example usage
num_steps = 5  # Number of forecast steps
num_stocks = 3  # Number of stocks
returns_matrix = np.random.rand(num_steps, num_stocks)  # Replace with your mean forecast matrix
variances_matrix = np.random.rand(num_steps, num_stocks)  # Replace with your variance forecast matrix
cov_matrices = np.array([np.diag(variances) for variances in variances_matrix])  # Assuming independent stocks for simplicity
max_variance = 0.2  # Replace with your specific constraint on variance

optimal_weights_matrix = optimize_weights_for_forecast_steps(returns_matrix, cov_matrices, max_variance)

print("Optimal Weights Matrix:")
print(optimal_weights_matrix)


optimal_weights_matrix.sum(axis=1)

import numpy as np
from scipy.optimize import minimize

def objective(weights, returns, cov_matrix):
    portfolio_return = np.dot(returns, weights)
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = -portfolio_return / portfolio_volatility  # Minimize the negative Sharpe ratio
    return sharpe_ratio

def optimize_portfolio(returns, cov_matrix, max_variance):
    num_stocks = len(returns)

    # Constraint: weights sum to 1
    constraints = ({'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1},
                   {'type': 'ineq', 'fun': lambda weights: max_variance - np.dot(weights.T, np.dot(cov_matrix, weights))})

    # Initial guess: Equal weights
    initial_weights = np.ones(num_stocks) / num_stocks

    # Minimize the negative Sharpe ratio
    result = minimize(objective, initial_weights, args=(returns, cov_matrix), method='SLSQP', constraints=constraints)

    optimal_weights = result.x

    return optimal_weights

# Example usage
num_stocks = 3
returns = np.array([0.5, 0.8, 0.12])  # Replace with your mean forecast for each stock
variances = np.array([0.02, 0.03, 0.05])  # Replace with your variance forecast for each stock
cov_matrix = np.diag(variances)  # Assuming independent stocks for simplicity
max_variance = 0.1  # Replace with your specific constraint on variance

optimal_weights = optimize_portfolio(returns, cov_matrix, max_variance)

print("Optimal Weights:", optimal_weights)


optimal_weights.sum()